export default [
  { id: 1, label: 'AKATEKO' },
  { id: 2, label: 'AMUZGO' },
  { id: 3, label: 'AWAKATEKO' },
  { id: 4, label: 'AYAPANECO' },
  { id: 5, label: 'CORA' },
  { id: 6, label: 'CUCAPÁ' },
  { id: 7, label: 'CUICATECO' },
  { id: 8, label: 'CHATINO' },
  { id: 9, label: 'CHICHIMECO JONAZ' },
  { id: 10, label: 'CHINANTECO' },
  { id: 11, label: 'CHOCHOLTECO' },
  { id: 12, label: 'CHONTAL DE OAXACA' },
  { id: 13, label: 'CHONTAL DE TABASCO' },
  { id: 14, label: 'CHUJ' },
  { id: 15, label: 'CH’OL' },
  { id: 16, label: 'GUARIJÍO' },
  { id: 17, label: 'HUASTECO' },
  { id: 18, label: 'HUAVE' },
  { id: 19, label: 'HUICHOL' },
  { id: 20, label: 'IXCATECO' },
  { id: 21, label: 'IXIL' },
  { id: 22, label: 'JAKALTEKO' },
  { id: 23, label: 'KAQCHIKEL' },
  { id: 24, label: 'KICKAPOO' },
  { id: 25, label: 'KILIWA' },
  { id: 26, label: 'KUMIAI' },
  { id: 27, label: 'KU’AHL' },
  { id: 28, label: 'K’ICHE’' },
  { id: 29, label: 'LACANDÓN' },
  { id: 30, label: 'MAM' },
  { id: 31, label: 'MATLATZINCA' },
  { id: 32, label: 'MAYA' },
  { id: 33, label: 'MAYO' },
  { id: 34, label: 'MAZAHUA' },
  { id: 35, label: 'MAZATECO' },
  { id: 36, label: 'MIXE' },
  { id: 37, label: 'MIXTECO' },
  { id: 38, label: 'NÁHUATL' },
  { id: 39, label: 'OLUTECO' },
  { id: 40, label: 'OTOMÍ' },
  { id: 41, label: 'PAIPAI' },
  { id: 42, label: 'PAME' },
  { id: 43, label: 'PÁPAGO' },
  { id: 44, label: 'PIMA' },
  { id: 45, label: 'POPOLOCA' },
  { id: 46, label: 'POPOLUCA DE LA SIERRA' },
  { id: 47, label: 'QATO’K' },
  { id: 48, label: 'Q’ANJOB’AL' },
  { id: 49, label: 'Q’EQCHÍ’' },
  { id: 50, label: 'SAYULTECO' },
  { id: 51, label: 'SERI' },
  { id: 52, label: 'TARAHUMARA' },
  { id: 53, label: 'TARASCO' },
  { id: 54, label: 'TEKO' },
  { id: 55, label: 'TEPEHUA' },
  { id: 56, label: 'OTRAS LENGUAS INDÍGENAS DE AMÉRICA' },
  { id: 57, label: 'NO SABE/NO RESPONDE' },
];
