export default [
  { id: 1, label: "AGUASCALIENTES" },
  { id: 2, label: "BAJA CALIFORNIA" },
  { id: 3, label: "BAJA CALIFORNIA SUR" },
  { id: 4, label: "CAMPECHE" },
  { id: 5, label: "COAHUILA DE ZARAGOZA" },
  { id: 6, label: "COLIMA" },
  { id: 7, label: "CHIAPAS" },
  { id: 8, label: "CHIHUAHUA" },
  { id: 9, label: "CIUDAD DE MÉXICO" },
  { id: 10, label: "DURANGO" },
  { id: 11, label: "GUANAJUATO" },
  { id: 12, label: "GUERRERO" },
  { id: 13, label: "HIDALGO" },
  { id: 14, label: "JALISCO" },
  { id: 15, label: "MÉXICO" },
  { id: 16, label: "MICHOACÁN DE OCAMPO" },
  { id: 17, label: "MORELOS" },
  { id: 18, label: "NAYARIT" },
  { id: 19, label: "NUEVO LEÓN" },
  { id: 20, label: "OAXACA" },
  { id: 21, label: "PUEBLA" },
  { id: 22, label: "QUERÉTARO" },
  { id: 23, label: "QUINTANA ROO" },
  { id: 24, label: "SAN LUIS POTOSÍ" },
  { id: 25, label: "SINALOA" },
  { id: 26, label: "SONORA" },
  { id: 27, label: "TABASCO" },
  { id: 28, label: "TAMAULIPAS" },
  { id: 29, label: "TLAXCALA" },
  { id: 30, label: "VERACRUZ DE IGNACIO DE LA LLAVE" },
  { id: 31, label: "YUCATÁN" },
  { id: 32, label: "ZACATECAS" },
  { id: 33, label: "NO SABE/NO RESPONDE" },
];
