export default [
  { id: 1, label: "ANGUILA*" },
  { id: 2, label: "ANTÁRTIDA" },
  { id: 3, label: "ANTIGUA REPÚBLICA YUGOSLAVA DE MACEDONIA" },
  { id: 4, label: "ANTIGUA Y BARBUDA" },
  { id: 5, label: "ANTILLAS NEERLANDESAS" },
  { id: 6, label: "ARUBA" },
  { id: 7, label: "BARBADOS" },
  { id: 8, label: "BELICE" },
  { id: 9, label: "BERMUDAS*" },
  { id: 10, label: "BIRMANIA" },
  { id: 11, label: "BOSNIA Y HERZEGOVINA" },
  { id: 12, label: "BURKINA FASO" },
  { id: 13, label: "CANADÁ" },
  { id: 14, label: "CHECOSLOVAQUIA" },
  { id: 15, label: "CONFEDERACIÓN SUIZA" },
  { id: 16, label: "CURAZAO" },
  { id: 17, label: "EMIRATOS ÁRABES UNIDOS" },
  { id: 18, label: "ESLOVAQUIA" },
  { id: 19, label: "ESTADO DE ERITREA" },
  { id: 20, label: "ESTADO DE ISRAEL" },
  { id: 21, label: "ESTADO DE KUWAIT" },
  { id: 22, label: "ESTADO DE LA CIUDAD DEL VATICANO" },
  { id: 23, label: "ESTADO DE LIBIA" },
  { id: 24, label: "ESTADO DE PALESTINA" },
  { id: 25, label: "ESTADO DE QATAR" },
  { id: 26, label: "ESTADO INDEPENDIENTE DE PAPÚA NUEVA GUINEA" },
  { id: 27, label: "ESTADO INDEPENDIENTE DE SAMOA" },
  { id: 28, label: "ESTADO LIBRE ASOCIADO DE PUERTO RICO" },
  { id: 29, label: "ESTADO PLURINACIONAL DE BOLIVIA" },
  { id: 30, label: "ESTADOS FEDERADOS DE MICRONESIA" },
  { id: 31, label: "ESTADOS UNIDOS DE AMÉRICA" },
  { id: 32, label: "FEDERACIÓN DE RUSIA" },
  { id: 33, label: "FEDERACIÓN DE SAN CRISTÓBAL Y NIEVES" },
  { id: 34, label: "GEORGIA" },
  { id: 35, label: "GIBRALTAR*" },
  { id: 36, label: "GRAN DUCADO DE LUXEMBURGO" },
  { id: 37, label: "GRANADA" },
  { id: 38, label: "GROENLANDIA" },
  { id: 39, label: "GUADALUPE" },
  { id: 40, label: "GUAM*" },
  { id: 41, label: "GUAYANA FRANCESA" },
  { id: 42, label: "HONG KONG" },
  { id: 43, label: "HUNGRÍA" },
  { id: 44, label: "ISLA BOUVET" },
  { id: 45, label: "ISLA CHRISTMAS" },
  { id: 46, label: "ISLA DE MAN" },
  { id: 47, label: "ISLA DE SINT MAARTEN" },
  { id: 48, label: "ISLA NORFOLK" },
  { id: 49, label: "ISLA SANTA HELENA*" },
  { id: 50, label: "ISLA WAKE" },
  { id: 51, label: "ISLAS CAIMÁN*" },
  { id: 52, label: "ISLAS COCOS (KEELING)" },
  { id: 53, label: "ISLAS COOK" },
  { id: 54, label: "ISLAS FEROE" },
  { id: 55, label: "ISLAS HEARD Y MCDONALD" },
  { id: 56, label: "ISLAS MALVINAS*" },
  { id: 57, label: "ISLAS PITCAIRN, HENDERSON, DUCIE Y OENO*" },
  { id: 58, label: "ISLAS REMOTAS MENORES DE LOS ESTADOS UNIDOS" },
  { id: 59, label: "ISLAS SALOMÓN" },
  { id: 60, label: "ISLAS SVALBARD Y JAN MAYEN" },
  { id: 61, label: "ISLAS TURCAS Y CAICOS*" },
  { id: 62, label: "ISLAS VÍRGENES BRITÁNICAS*" },
  { id: 63, label: "ISLAS VÍRGENES DE LOS ESTADOS UNIDOS*" },
  { id: 64, label: "ISLAS WALLIS Y FUTUNA" },
  { id: 65, label: "JAMAICA" },
  { id: 66, label: "JAPÓN" },
  { id: 67, label: "MACAO" },
  { id: 68, label: "MALASIA" },
  { id: 69, label: "MANCOMUNIDAD DE AUSTRALIA" },
  { id: 70, label: "MANCOMUNIDAD DE DOMINICA" },
  { id: 71, label: "MANCOMUNIDAD DE LAS BAHAMAS" },
  { id: 72, label: "MANCOMUNIDAD DE LAS ISLAS MARIANAS DEL NORTE" },
  { id: 73, label: "MARTINICA" },
  { id: 74, label: "MÉXICO" },
  { id: 75, label: "MONGOLIA" },
  { id: 76, label: "MONTSERRAT*" },
  { id: 77, label: "NIUE" },
  { id: 78, label: "NO ESPECIFICADO" },
  { id: 79, label: "NUEVA CALEDONIA" },
  { id: 80, label: "NUEVA ZELANDIA" },
  { id: 81, label: "OTRO" },
  { id: 82, label: "POLINESIA FRANCESA" },
  { id: 83, label: "PRINCIPADO DE ANDORRA" },
  { id: 84, label: "PRINCIPADO DE LIECHTENSTEIN" },
  { id: 85, label: "PRINCIPADO DE MÓNACO" },
  { id: 86, label: "REINO DE ARABIA SAUDITA" },
  { id: 87, label: "REINO DE BAHRÉIN" },
  { id: 88, label: "REINO DE BÉLGICA" },
  { id: 89, label: "REINO DE BUTÁN" },
  { id: 90, label: "REINO DE CAMBOYA" },
  { id: 91, label: "REINO DE DINAMARCA" },
  { id: 92, label: "REINO DE ESPAÑA" },
  { id: 93, label: "REINO DE LESOTHO" },
  { id: 94, label: "REINO DE LOS PAÍSES BAJOS" },
  { id: 95, label: "REINO DE MARRUECOS" },
  { id: 96, label: "REINO DE NORUEGA" },
  { id: 97, label: "REINO DE SUAZILANDIA" },
  { id: 98, label: "REINO DE SUECIA" },
  { id: 99, label: "REINO DE TAILANDIA" },
  { id: 100, label: "REINO DE TONGA" },
  { id: 101, label: "REINO HACHEMITA DE JORDANIA" },
  { id: 102, label: "REINO UNIDO (C. BRIT. DEL EXTRANJERO)" },
  { id: 103, label: "REINO UNIDO (C. DE DEPEN. TERRIT. BRIT.)" },
  { id: 104, label: "REINO UNIDO (C. DE NAL. BRIT. DEL EXT.)" },
  { id: 105, label: "REINO UNIDO (CIUDADANO BRITANICO)" },
  { id: 106, label: "REINO UNIDO (PERSONA BAJO PROTEC. BRIT.)" },
  { id: 107, label: "REINO UNIDO (SUBDITO BRITANICO)" },
  { id: 108, label: "REINO UNIDO DE GRAN BRETAÑA E IRLANDA DEL NORTE" },
  { id: 109, label: "REPÚBLICA ÁRABE DE EGIPTO" },
  { id: 110, label: "REPÚBLICA ÁRABE SAHARAUI DEMOCRÁTICA*" },
  { id: 111, label: "REPÚBLICA ÁRABE SIRIA" },
  { id: 112, label: "REPÚBLICA ARGELINA DEMOCRÁTICA Y POPULAR" },
  { id: 113, label: "REPÚBLICA ARGENTINA" },
  { id: 114, label: "REPÚBLICA BOLIVARIANA DE VENEZUELA" },
  { id: 115, label: "REPÚBLICA CENTROAFRICANA" },
  { id: 116, label: "REPÚBLICA CHECA" },
  { id: 117, label: "REPÚBLICA COOPERATIVA DE GUYANA" },
  { id: 118, label: "REPÚBLICA DE ALBANIA" },
  { id: 119, label: "REPÚBLICA DE ANGOLA" },
  { id: 120, label: "REPÚBLICA DE ARMENIA" },
  { id: 121, label: "REPÚBLICA DE AUSTRIA" },
  { id: 122, label: "REPÚBLICA DE AZERBAIYÁN" },
  { id: 123, label: "REPÚBLICA DE BENÍN" },
  { id: 124, label: "REPÚBLICA DE BIELORRUSIA" },
  { id: 125, label: "REPÚBLICA DE BOTSUANA" },
  { id: 126, label: "REPÚBLICA DE BULGARIA" },
  { id: 127, label: "REPÚBLICA DE BURUNDI" },
  { id: 128, label: "REPÚBLICA DE CABO VERDE" },
  { id: 129, label: "REPÚBLICA DE CAMERÚN" },
  { id: 130, label: "REPÚBLICA DE CHILE" },
  { id: 131, label: "REPÚBLICA DE CHIPRE" },
  { id: 132, label: "REPÚBLICA DE COLOMBIA" },
  { id: 133, label: "REPÚBLICA DE COREA" },
  { id: 134, label: "REPÚBLICA DE COSTA DE MARFIL" },
  { id: 135, label: "REPÚBLICA DE COSTA RICA" },
  { id: 136, label: "REPÚBLICA DE CROACIA" },
  { id: 137, label: "REPÚBLICA DE CUBA" },
  { id: 138, label: "REPÚBLICA DE EL SALVADOR" },
  { id: 139, label: "REPÚBLICA DE ESLOVENIA" },
  { id: 140, label: "REPÚBLICA DE ESTONIA" },
  { id: 141, label: "REPÚBLICA DE FIJI" },
  { id: 142, label: "REPÚBLICA DE FILIPINAS" },
  { id: 143, label: "REPÚBLICA DE FINLANDIA" },
  { id: 144, label: "REPÚBLICA DE GAMBIA" },
  { id: 145, label: "REPÚBLICA DE GHANA" },
  { id: 146, label: "REPÚBLICA DE GUATEMALA" },
  { id: 147, label: "REPÚBLICA DE GUINEA" },
  { id: 148, label: "REPÚBLICA DE GUINEA BISSAU" },
  { id: 149, label: "REPÚBLICA DE GUINEA ECUATORIAL" },
  { id: 150, label: "REPÚBLICA DE HAITÍ" },
  { id: 151, label: "REPÚBLICA DE HONDURAS" },
  { id: 152, label: "REPÚBLICA DE INDONESIA" },
  { id: 153, label: "REPÚBLICA DE IRAK" },
  { id: 154, label: "REPÚBLICA DE IRLANDA" },
  { id: 155, label: "REPÚBLICA DE ISLANDIA" },
  { id: 156, label: "REPÚBLICA DE KAZAJSTÁN" },
  { id: 157, label: "REPÚBLICA DE KENIA" },
  { id: 158, label: "REPÚBLICA DE KIRIBATI" },
  { id: 159, label: "REPÚBLICA DE LA INDIA" },
  { id: 160, label: "REPÚBLICA DE LAS ISLAS MARSHALL" },
  { id: 161, label: "REPÚBLICA DE LAS SEYCHELLES" },
  { id: 162, label: "REPÚBLICA DE LETONIA" },
  { id: 163, label: "REPÚBLICA DE LIBERIA" },
  { id: 164, label: "REPÚBLICA DE LITUANIA" },
  { id: 165, label: "REPÚBLICA DE MADAGASCAR" },
  { id: 166, label: "REPÚBLICA DE MALAUI" },
  { id: 167, label: "REPÚBLICA DE MALDIVAS" },
  { id: 168, label: "REPÚBLICA DE MALÍ" },
  { id: 169, label: "REPÚBLICA DE MALTA" },
  { id: 170, label: "REPÚBLICA DE MAURICIO" },
  { id: 171, label: "REPÚBLICA DE MOLDAVIA" },
  { id: 172, label: "REPÚBLICA DE MONTENEGRO" },
  { id: 173, label: "REPÚBLICA DE MOZAMBIQUE" },
  { id: 174, label: "REPÚBLICA DE NAMIBIA" },
  { id: 175, label: "REPÚBLICA DE NAURU" },
  { id: 176, label: "REPÚBLICA DE NICARAGUA" },
  { id: 177, label: "REPÚBLICA DE PALAOS" },
  { id: 178, label: "REPÚBLICA DE PANAMÁ" },
  { id: 179, label: "REPÚBLICA DE POLONIA" },
  { id: 180, label: "REPÚBLICA DE RUANDA" },
  { id: 181, label: "REPÚBLICA DE SAN MARINO" },
  { id: 182, label: "REPÚBLICA DE SENEGAL" },
  { id: 183, label: "REPÚBLICA DE SERBIA" },
  { id: 184, label: "REPÚBLICA DE SIERRA LEONA" },
  { id: 185, label: "REPÚBLICA DE SINGAPUR" },
  { id: 186, label: "REPÚBLICA DE SUDÁFRICA" },
  { id: 187, label: "REPÚBLICA DE SUDÁN DEL SUR" },
  { id: 188, label: "REPÚBLICA DE SURINAM" },
  { id: 189, label: "REPÚBLICA DE TAYIKISTÁN" },
  { id: 190, label: "REPÚBLICA DE TRINIDAD Y TOBAGO" },
  { id: 191, label: "REPÚBLICA DE TURQUÍA" },
  { id: 192, label: "REPÚBLICA DE UGANDA" },
  { id: 193, label: "REPÚBLICA DE UZBEKISTÁN" },
  { id: 194, label: "REPÚBLICA DE VANUATU" },
  { id: 195, label: "REPÚBLICA DE YEMEN" },
  { id: 196, label: "REPÚBLICA DE YIBUTI" },
  { id: 197, label: "REPÚBLICA DE ZAMBIA" },
  { id: 198, label: "REPÚBLICA DE ZIMBABUE" },
  { id: 199, label: "REPÚBLICA DEL CHAD" },
  { id: 200, label: "REPÚBLICA DEL CONGO" },
  { id: 201, label: "REPÚBLICA DEL ECUADOR" },
  { id: 202, label: "REPÚBLICA DEL NÍGER" },
  { id: 203, label: "REPÚBLICA DEL PARAGUAY" },
  { id: 204, label: "REPÚBLICA DEL PERÚ" },
  { id: 205, label: "REPÚBLICA DEL SUDÁN" },
  { id: 206, label: "REPÚBLICA DEMOCRÁTICA DE SANTO TOMÉ Y PRÍNCIPE" },
  { id: 207, label: "REPÚBLICA DEMOCRÁTICA DE TIMOR ORIENTAL" },
  { id: 208, label: "REPÚBLICA DEMOCRÁTICA DEL CONGO" },
  { id: 209, label: "REPÚBLICA DEMOCRÁTICA FEDERAL DE ETIOPÍA" },
  { id: 210, label: "REPÚBLICA DEMOCRÁTICA POPULAR LAO" },
  { id: 211, label: "REPÚBLICA DOMINICANA" },
  { id: 212, label: "REPÚBLICA ESLOVACA" },
  { id: 213, label: "REPÚBLICA FEDERAL DE ALEMANIA" },
  { id: 214, label: "REPÚBLICA FEDERAL DE NIGERIA" },
  { id: 215, label: "REPÚBLICA FEDERAL DE SOMALIA" },
  { id: 216, label: "REPÚBLICA FEDERAL DEMOCRÁTICA DE NEPAL" },
  { id: 217, label: "REPÚBLICA FEDERATIVA DE BRASIL" },
  { id: 218, label: "REPÚBLICA FRANCESA" },
  { id: 219, label: "REPÚBLICA GABONESA" },
  { id: 220, label: "REPÚBLICA HELÉNICA" },
  { id: 221, label: "REPÚBLICA ISLÁMICA DE AFGANISTÁN" },
  { id: 222, label: "REPÚBLICA ISLÁMICA DE IRÁN" },
  { id: 223, label: "REPÚBLICA ISLÁMICA DE MAURITANIA" },
  { id: 224, label: "REPÚBLICA ISLÁMICA DE PAKISTÁN" },
  { id: 225, label: "REPÚBLICA ITALIANA" },
  { id: 226, label: "REPÚBLICA KIRGUISA" },
  { id: 227, label: "REPÚBLICA LIBANESA" },
  { id: 228, label: "REPÚBLICA ORIENTAL DEL URUGUAY" },
  { id: 229, label: "REPÚBLICA POPULAR CHINA" },
  { id: 230, label: "REPÚBLICA POPULAR DE BANGLADESH" },
  { id: 231, label: "REPÚBLICA POPULAR DEMOCRÁTICA DE COREA" },
  { id: 232, label: "REPÚBLICA PORTUGUESA" },
  { id: 233, label: "REPÚBLICA SOCIALISTA DE VIETNAM" },
  { id: 234, label: "REPÚBLICA SOCIALISTA DEMOCRÁTICA DE SRI LANKA" },
  { id: 235, label: "REPÚBLICA TOGOLESA" },
  { id: 236, label: "REPÚBLICA TUNECINA" },
  { id: 237, label: "REPÚBLICA UNIDA DE TANZANIA" },
  { id: 238, label: "REUNION" },
  { id: 239, label: "RUMANIA" },
  { id: 240, label: "SAÍNT PIERRE Y MIQUELÓN" },
  { id: 241, label: "SAMOA AMERICANA*" },
  { id: 242, label: "SAN VICENTE Y LAS GRANADINAS" },
  { id: 243, label: "SANTA LUCÍA" },
  { id: 244, label: "SE IGNORA" },
  { id: 245, label: "SULTANATO DE BRUNÉI" },
  { id: 246, label: "SULTANATO DE OMÁN" },
  { id: 247, label: "TAIWÁN" },
  { id: 248, label: "TERRITORIO BRITÁNICO DEL OCEANO ÍNDICO" },
  { id: 249, label: "TERRITORIOS FRANCESES DEL SUR" },
  { id: 250, label: "TOKELAU*" },
  { id: 251, label: "TURKMENISTÁN" },
  { id: 252, label: "TUVALU" },
  { id: 253, label: "UCRANIA" },
  { id: 254, label: "UNIÓN DE LAS COMORAS" },
  { id: 255, label: "UNIÓN DE MYANMAR" },
  { id: 256, label: "YUGOSLAVIA" },
  { id: 257, label: "ZONA NEUTRAL" },
];
