export default [
  { id: 1, label: 'AMPLIACIÓN' },
  { id: 2, label: 'ANDADOR' },
  { id: 3, label: 'AVENIDA' },
  { id: 4, label: 'BOULEVARD' },
  { id: 5, label: 'CALLE' },
  { id: 6, label: 'CALLEJÓN' },
  { id: 7, label: 'CALZADA' },
  { id: 8, label: 'CERRADA' },
  { id: 9, label: 'CIRCUITO' },
  { id: 10, label: 'CIRCUNVALACIÓN' },
  { id: 11, label: 'CONTINUACIÓN' },
  { id: 12, label: 'CORREDOR' },
  { id: 13, label: 'DIAGONAL' },
  { id: 14, label: 'EJE VIAL' },
  { id: 15, label: 'PASAJE PEATONAL' },
  { id: 16, label: 'PERIFÉRICO' },
  { id: 17, label: 'PRIVADA' },
  { id: 18, label: 'PROLONGACIÓN' },
  { id: 19, label: 'RETORNO' },
  { id: 20, label: 'VIADUCTO' },
];
