export default [
  { id: 1, label: "NINGUNA" },
  { id: 2, label: "PREESCOLAR" },
  { id: 3, label: "PRIMARIA INCOMPLETA" },
  { id: 4, label: "PRIMARIA COMPLETA" },
  { id: 5, label: "SECUNDARIA INCOMPLETA" },
  { id: 6, label: "SECUNDARIA COMPLETA" },
  { id: 7, label: "BACHILLERATO O PREPARATORIA INCOMPLETA" },
  { id: 8, label: "BACHILLERATO O PREPARATORIA COMPLETA" },
  { id: 9, label: "BACHILLETARO TECNOLÓGICO COMPLETO" },
  { id: 10, label: "BACHILLETARO TECNOLÓGICO INCOMPLETO" },
  {
    id: 11,
    label: "ESTUDIOS TÉCNICOS O COMERCIALES CON PRIMARIA TERMINADA INCOMPLETO",
  },
  {
    id: 12,
    label: "ESTUDIOS TÉCNICOS O COMERCIALES CON PRIMARIA TERMINADA COMPLETO",
  },
  {
    id: 13,
    label:
      "ESTUDIOS TÉCNICOS O COMERCIALES CON SECUNDARIA TERMINADA INCOMPLETO",
  },
  {
    id: 14,
    label: "ESTUDIOS TÉCNICOS O COMERCIALES CON SECUNDARIA TERMINADA COMPLETO",
  },
  {
    id: 15,
    label:
      "ESTUDIOS TÉCNICOS O COMERCIALES CON PREPARATORIA TERMINADA INCOMPLETO",
  },
  {
    id: 16,
    label:
      "ESTUDIOS TÉCNICOS O COMERCIALES CON PREPARATORIA TERMINADA COMPLETO",
  },
  { id: 17, label: "NORMAL CON PRIMARIA O SECUNDARIA TERMINADA INCOMPLETA" },
  { id: 18, label: "NORMAL CON PRIMARIA O SECUNDARIA TERMINADA COMPLETA" },
  { id: 19, label: "NORMAL CON LICENCIATURA, INCOMPLETA" },
  { id: 20, label: "NORMAL CON LICENCIATURA, COMPLETA" },
  { id: 21, label: "PROFESIONAL" },
  { id: 22, label: "ESPECIALIDAD" },
  { id: 23, label: "MAESTRÍA" },
  { id: 24, label: "DOCTORADO" },
  { id: 25, label: "NO APLICA" },
  { id: 26, label: "NO SABE/NO RESPONDE" },
];
